// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlVdwu_Amjl5ySaaEeYD8GeHnRsxPLUFo',
    appId: '1:552434533572:web:bac9d5aa15153daf9db591',
    messagingSenderId: '552434533572',
    projectId: 'chirashi-6c92d',
    authDomain: 'chirashi-6c92d.firebaseapp.com',
    storageBucket: 'chirashi-6c92d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsOsQcTfbVXDow2CRz1AmqrvIQGuoljg',
    appId: '1:552434533572:android:f6cbd3b2486dbd4e9db591',
    messagingSenderId: '552434533572',
    projectId: 'chirashi-6c92d',
    storageBucket: 'chirashi-6c92d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtERg3JMkLPaLkmg8mPZ3-LCo6qmbKCk',
    appId: '1:552434533572:ios:a748423cfdc9d8ad9db591',
    messagingSenderId: '552434533572',
    projectId: 'chirashi-6c92d',
    storageBucket: 'chirashi-6c92d.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxtERg3JMkLPaLkmg8mPZ3-LCo6qmbKCk',
    appId: '1:552434533572:ios:a748423cfdc9d8ad9db591',
    messagingSenderId: '552434533572',
    projectId: 'chirashi-6c92d',
    storageBucket: 'chirashi-6c92d.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlVdwu_Amjl5ySaaEeYD8GeHnRsxPLUFo',
    appId: '1:552434533572:web:0241c8b89f8a79909db591',
    messagingSenderId: '552434533572',
    projectId: 'chirashi-6c92d',
    authDomain: 'chirashi-6c92d.firebaseapp.com',
    storageBucket: 'chirashi-6c92d.firebasestorage.app',
  );
}
