// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA9kfohE5-tDrCODzM3pY8H1thKPapujQ',
    appId: '1:74063304979:web:80a68fd44de65ad10822e6',
    messagingSenderId: '74063304979',
    projectId: 'kakeiboard-17eea',
    authDomain: 'kakeiboard-17eea.firebaseapp.com',
    storageBucket: 'kakeiboard-17eea.firebasestorage.app',
    measurementId: 'G-5CNQMV4TRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1MTKYFqC3bYDlWxdxZm627dY_EnpUJ8',
    appId: '1:74063304979:android:e6fc59841d14fb4e0822e6',
    messagingSenderId: '74063304979',
    projectId: 'kakeiboard-17eea',
    storageBucket: 'kakeiboard-17eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMHd_PnyqQFm891z-lfwHe8khyigT7VSM',
    appId: '1:74063304979:ios:e5178cd0688522110822e6',
    messagingSenderId: '74063304979',
    projectId: 'kakeiboard-17eea',
    storageBucket: 'kakeiboard-17eea.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMHd_PnyqQFm891z-lfwHe8khyigT7VSM',
    appId: '1:74063304979:ios:e5178cd0688522110822e6',
    messagingSenderId: '74063304979',
    projectId: 'kakeiboard-17eea',
    storageBucket: 'kakeiboard-17eea.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA9kfohE5-tDrCODzM3pY8H1thKPapujQ',
    appId: '1:74063304979:web:c6c3d7b402d173c90822e6',
    messagingSenderId: '74063304979',
    projectId: 'kakeiboard-17eea',
    authDomain: 'kakeiboard-17eea.firebaseapp.com',
    storageBucket: 'kakeiboard-17eea.firebasestorage.app',
    measurementId: 'G-L6D81SBLQ0',
  );

}